### ISSUE TITLE
[BUG] BeeF docker image not found

### ISSUE THREAD

**Issue by tperich** [cybersecsi/HOUDINI#12]
**Describe the bug**

The image for BeeF cannot be found by docker.

Docker output:
```
user@server$: sudo docker run -p 3000:3000 -p 6789:6789 -p 61985:61985 -p 61986:61986 --name beef beef
Unable to find image 'beef:latest' locally
docker: Error response from daemon: pull access denied for beef, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**To Reproduce**

Run the command above.

**Expected behavior**

The docker container should run.

**Comment by thelicato** [comment]
Hi, *BeeF* is an open source tool that you can find [here](https://github.com/beefproject/beef). As you can see there is a Dockerfile that you can easily build. If you are not familiar with building Docker Images here is there [Installation page](https://github.com/beefproject/beef/wiki/Installation#docker-setup) of BeeF itself.

Be aware that **we do not** provide all the Docker images that you find on HOUDINI, we only provide Docker images that start with the ``secsi`` repository. Even in that case you should refer to the [RAUDI](https://github.com/cybersecsi/RAUDI) project.

**Comment by tperich** [comment]
@thelicato Thank you for the detailed answer. In that case, wouldn't the listing on https://houdini.secsi.io/ be misleading as it clearly displays a copy button to copy-paste the docker command which doesn't work? Perhaps I have missed a point here, are the commands displayed just as examples?

**Comment by tperich** [comment]
Thank you for the clarification! It now makes sense.
