### ISSUE TITLE
Arm (Mac M1) support

### ISSUE THREAD

**Issue by egelmex** [cybersecsi/HOUDINI#2]
Simplify support for people running docker on arm. Ideally having all images built for ARM, however a UI feature that flags that ARM is being in use and added the option `--platform linux/amd64` where needed would be helpful.

**Comment by thelicato** [comment]
This is quite an interesting idea. If you look closely you will find out that **a lot** of images have the '*secsi*' organization. Those images are automatically built and updated by another tool we developed: [RAUDI](https://github.com/cybersecsi/RAUDI) (which stands for Regularly and Automatically Updated Docker Images). 
In this tool we use ``buildx`` to build images, so it would be very easy to also build for ``linux/arm64``. In this way yuo would have **a lot** of images that are natively compatible with M1. For the other we would probably add it manually (there are some APIs, but we don't want to make a lot of requests).

For the ``run`` command we can probably add the information somewhere and then you manually add the option ``--platform linux/amd64``. This can be an easy and quick fix. As soon as we find the time we can add like a checkbox to enable this option (I don't want to add it in every command even if the user does not need it).
